spring.application.name=magiarium_api
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/magiarium_db
spring.datasource.username=${?????}
spring.datasource.password=${?????}
spring.jpa.database=MYSQL